---
sidebar: sidebar 
permalink: trident-docker/prereqs-docker.html 
keywords: deploy, astra trident, docker, trident for docker, nfs, iscsi, protcol, nfs protocol, iscsi protocol, configure host, host config, nvme/tcp, nvme 
summary: 在部署 Astra Trident 之前，您必须在主机上安装和配置必要的协议前提条件。 
---
= 部署的前提条件
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在部署 Astra Trident 之前，您必须在主机上安装和配置必要的协议前提条件。



== 验证要求

* 验证您的部署是否满足所有要求 link:../trident-get-started/requirements.html["要求"]。
* 验证您是否安装了受支持的 Docker 版本。如果您的 Docker 版本已过时， https://docs.docker.com/engine/install/["安装或更新它"^]。
+
[listing]
----
docker --version
----
* 验证是否已在主机上安装和配置协议前提条件。




=== NFS工具

使用适用于您的操作系统的命令安装NFS工具。

[role="tabbed-block"]
====
.RHEL 8+
--
[listing]
----
sudo yum install -y nfs-utils
----
--
.Ubuntu
--
[listing]
----
sudo apt-get install -y nfs-common
----
--
====

WARNING: 安装NFS工具后重新启动工作节点、以防止在将卷连接到容器时失败。



=== iSCSI工具

使用适用于您的操作系统的命令安装iSCSI工具。

[role="tabbed-block"]
====
.RHEL 8+
--
. 安装以下系统软件包：
+
[listing]
----
sudo yum install -y lsscsi iscsi-initiator-utils sg3_utils device-mapper-multipath
----
. 检查 iscsi-initiator-utils 版本是否为 6.2.0.877-2.el7 或更高版本：
+
[listing]
----
rpm -q iscsi-initiator-utils
----
. 将扫描设置为手动：
+
[listing]
----
sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf
----
. 启用多路径：
+
[listing]
----
sudo mpathconf --enable --with_multipathd y --find_multipaths n
----
+

NOTE: 确保 `detc/multipath.conf` contains `find_multipaths no` under` efaults `.

. 确保 `iscsid` 和 `multipathd` 正在运行：
+
[listing]
----
sudo systemctl enable --now iscsid multipathd
----
. 启用并启动 `iSCSI` ：
+
[listing]
----
sudo systemctl enable --now iscsi
----


--
.Ubuntu
--
. 安装以下系统软件包：
+
[listing]
----
sudo apt-get install -y open-iscsi lsscsi sg3-utils multipath-tools scsitools
----
. 检查 open-iscsi 版本是否为 2.0.877-5ubuntu2.10 或更高版本（对于双子系统）或 2.0.877-7.1ubuntu6.1 或更高版本（对于 Focal ）：
+
[listing]
----
dpkg -l open-iscsi
----
. 将扫描设置为手动：
+
[listing]
----
sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf
----
. 启用多路径：
+
[listing]
----
sudo tee /etc/multipath.conf <<-'EOF'
defaults {
    user_friendly_names yes
    find_multipaths no
}
EOF
sudo systemctl enable --now multipath-tools.service
sudo service multipath-tools restart
----
+

NOTE: 确保 `detc/multipath.conf` contains `find_multipaths no` under` efaults `.

. 确保已启用并运行 `open-iscsi` 和 `multipath-tools` ：
+
[listing]
----
sudo systemctl status multipath-tools
sudo systemctl enable --now open-iscsi.service
sudo systemctl status open-iscsi
----


--
====


== NVMe工具

使用适用于您的操作系统的命令安装NVMe工具。

[NOTE]
====
* NVMe需要RHEL 9或更高版本。
* 如果Kubelnetes节点的内核版本太旧、或者NVMe软件包不适用于您的内核版本、您可能需要将节点的内核版本更新为具有NVMe软件包的版本。


====
[role="tabbed-block"]
====
.RHEL 9
--
[listing]
----
sudo yum install nvme-cli
sudo yum install linux-modules-extra-$(uname -r)
sudo modprobe nvme-tcp
----
--
.Ubuntu
--
[listing]
----
sudo apt install nvme-cli
sudo apt -y install linux-modules-extra-$(uname -r)
sudo modprobe nvme-tcp
----
--
====