---
sidebar: sidebar 
permalink: trident-rn.html 
keywords: 'what"s new, new features, enhancements, known issues, resolved issues, troubleshooting' 
summary: NetApp 不断改进和完善其产品和服务。以下是最新版 Astra Trident 中的一些最新功能，增强功能和错误修复。 
---
= 发行说明
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


发行说明提供了有关最新版本的 Astra Trident 中的新增功能，增强功能和错误修复的信息。


WARNING: 安装程序 zip 文件中提供的 `tridentctl` 二进制文件是经过测试且受支持的版本。请注意， zip 文件的 ` 或 Extras` 部分中提供的 `macos` 二进制文件未经过测试或不受支持。



== 22.01.1 中的新增功能

NetApp 不断改进和完善其产品和服务。以下是 Astra Trident 中的一些最新功能。对于先前版本，请参见 https://docs.netapp.com/us-en/trident/earlier-versions.html["文档的早期版本"]。


IMPORTANT: 如果要从先前的任何 Trident 版本升级并使用 Azure NetApp Files ，则 ``location`` config 参数现在是一个必填字段。



=== 修复

* 修复了已删除节点上的卷已取消发布的问题描述 。（link:https://github.com/NetApp/trident/issues/691["GitHub 问题描述 第 691 号"]）
* 修复了访问 ONTAP API 响应中聚合空间的 " 无 " 字段时的崩溃问题。




== 22.01.0 中的更改（从 22.10.1 开始）



=== 修复

* * Kubernetes ： * 增加大型集群的节点注册回退重试时间。
* 修复了问题描述 ，其中 azure-netapp-files 驱动程序可能会被同名的多个资源混淆。
* 如果使用括号指定 ONTAP SAN IPv6 数据 LIF ，则此 LIF 现在可以正常工作。
* 修复的问题描述 ，尝试导入已导入的卷时，返回的 EOF 将使 PVC 处于待定状态。（link:https://github.com/NetApp/trident/issues/489["GitHub 问题描述 489"]）
* 修复了在 SolidFire 卷上创建超过 32 个快照时 Astra Trident 性能下降的问题描述 。
* 在创建 SSL 证书时将 SHA-1 替换为 SHA-256 。
* 固定的 ANF 驱动程序，允许重复的资源名称并将操作限制在一个位置。
* 固定的 ANF 驱动程序，允许重复的资源名称并将操作限制在一个位置。




=== 增强功能

* Kubernetes 增强功能：
+
** 增加了对 Kubernetes 1.23 的支持。
** 通过 Trident 操作员或 Helm 安装 Trident Pod 时，为其添加计划选项。（link:https://github.com/NetApp/trident/issues/651["GitHub 问题描述 #651"^]）


* 在 GCP 驱动程序中允许跨区域卷。（link:https://github.com/NetApp/trident/issues/633["GitHub 问题描述 #633"^]）
* 为 ANF 卷增加了对 "unixPermissions" 选项的支持。（link:https://github.com/NetApp/trident/issues/666["GitHub 问题描述 #666"^]）




=== 已弃用

Trident REST 接口只能在 127.0.0.1 或 [ ：：： 1 ）地址处侦听和提供服务



== Astra Trident 21.10.1 中的变更


WARNING: v21.10.0 版本具有一个问题描述，在删除节点并将其重新添加回 Kubernetes 集群时， Trident 控制器可以将其置于 CrashLoopBackOff 状态。此问题描述在 v21.10.1 中得到了修复（ GitHub 问题描述 669 ）。



=== 修复

* 修复了在 GCP CVS 后端导入卷导致导入失败的潜在争用情况。
* 修复了一个问题描述，在删除节点并将其重新添加回 Kubernetes 集群时，可能会将 Trident 控制器置于 CrashLoopBackOff 状态（ GitHub 问题描述 669 ）。
* 修复了在未指定 SVM 名称的情况下不再发现 SVM 的问题描述（ GitHub 问题描述 612 ）。




== 21.10.0 中的更改（自 Astra Trident 21.07 以来）



=== 修复

* 修复了问题描述，其中无法将 XFS 卷的克隆挂载到与源卷相同的节点上（ GitHub 问题描述 514 ）。
* 修复了问题描述，其中 Astra Trident 在关闭时记录了致命错误（ GitHub 问题描述 597 ）。
* 与 Kubernetes 相关的修复程序：
+
** 使用 `ontap-NAS` 和 `ontap-nas-flexgroup` 驱动程序创建快照时，将卷的已用空间返回为最小还原大小（ GitHub 问题描述 645 ）。
** 修复了问题描述，其中 `无法扩展文件系统` 在调整卷大小后记录了错误（ GitHub 问题描述 560 ）。
** 修复了 POD 可能停留在 `正在终止` 状态的问题描述（ GitHub 问题描述 572 ）。
** 修复了 `ontap-san-economy-lun` FlexVol 可能已满快照 LUN 的情况（ GitHub 问题描述 533 ）。
** 使用不同映像修复了自定义 YAML 安装程序问题描述（ GitHub 问题描述 613" ）。
** 固定快照大小计算（ GitHub 问题描述 611 ）。
** 修复了问题描述，其中所有 Astra Trident 安装程序都可以将纯 Kubernetes 标识为 OpenShift （ GitHub 问题描述 639 ）。
** 修复了 Trident 操作员在无法访问 Kubernetes API 服务器时停止协调的问题（ GitHub 问题描述 599 ）。






=== 增强功能

* 为 GCP-CVS 性能卷增加了对 `unixPermissions` 选项的支持。
* 增加了对 GCP 中 600 GiB 到 1 TiB 范围内的扩展优化 CVS 卷的支持。
* Kubernetes 相关增强功能：
+
** 增加了对 Kubernetes 1.22 的支持。
** 已启用 Trident 操作员和 Helm 图表以使用 Kubernetes 1.22 （ GitHub 问题描述 628 ）。
** 已将操作员映像添加到 `tridentctl` images 命令（ GitHub 问题描述 570 ）中。






=== 实验增强功能

* 在 `ontap-san` 驱动程序中增加了对卷复制的支持。
* 增加了对 `ontap-nas-flexgroup` ， `ontap-san` 和 `ontap-nas-economy` 驱动程序的 * 技术预览 * REST 支持。




== 已知问题

已知问题用于确定可能会阻止您成功使用本产品的问题。

* 对于在其 StorageClass 中未指定 `FSType` 的卷， Astra Trident 现在会强制使用空的 `FSType` （`FSTtype=""` ）。使用 Kubernetes 1.17 或更高版本时， Trident 支持为 NFS 卷提供一个空的 `FSType` 。对于 iSCSI 卷，在使用安全上下文强制执行 `fsGroup` 时，您需要在 StorageClass 上设置 `FSType` 。
* 在多个 Astra Trident 实例之间使用后端时，每个后端配置文件对于 ONTAP 后端应具有不同的 `storagePrefix` 值，或者对于 SolidFire 后端使用不同的 `租户名称` 。Astra Trident 无法检测其他 Astra Trident 实例创建的卷。尝试在 ONTAP 或 SolidFire 后端创建现有卷会成功，因为 Astra Trident 会将卷创建视为一项幂等操作。如果 `storagePrefix` 或 `租户名称` 不存在差异，则在同一后端创建的卷可能会发生名称冲突。
* 安装 Astra Trident （使用 `tridentctl` 或 Trident 操作员）并使用 `tridentctl` 管理 Astra Trident 时，应确保设置 `KUBECONFIG` 环境变量。这是 `需要对` tridentctl 进行处理的 Kubernetes 集群进行指示的。在使用多个 Kubernetes 环境时，您应确保准确获取 `KUBECONFIG` 文件。
* 要对 iSCSI PV 执行联机空间回收，工作节点上的底层操作系统可能需要将挂载选项传递到卷。这一点适用于需要 `discard` 的 RHEL/RedHat CoreOS 实例 https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems["挂载选项"^]；确保中包含 Discard mountOption https://kubernetes.io/docs/concepts/storage/storage-classes/["`s存储类`"^] 支持联机块丢弃。
* 如果每个 Kubernetes 集群有多个 Astra Trident 实例，则 Astra Trident 将无法与其他实例通信，也无法发现它们创建的其他卷，如果集群中运行多个实例，则会导致意外的错误行为。每个 Kubernetes 集群只能有一个 Astra Trident 实例。
* 如果在 Astra Trident 脱机时从 Kubernetes 中删除了基于 Astra Trident 的 `StorageClass` 对象，则 Astra Trident 不会在恢复联机后从其数据库中删除相应的存储类。您应使用 `tridentctl` 或 REST API 删除这些存储类。
* 如果用户在删除相应的 PVC 之前删除了由 Astra Trident 配置的 PV ，则 Astra Trident 不会自动删除后备卷。您应通过 `tridentctl` 或 REST API 删除此卷。
* ONTAP 不能同时配置多个 FlexGroup ，除非聚合集对于每个配置请求是唯一的。
* 使用基于 IPv6 的 Astra Trident 时，应在后端定义中方括号内指定 `managementLIF` 和 `dataLIF` 。例如， `` FD20 ： 8b1e ： b258 ： 2000 ： f816 ： 3effe ： feec ： 0`` 。
* 如果将 `solidfire-san` 驱动程序与 OpenShift 4.5 结合使用，请确保底层工作节点使用 MD5 作为 CHAP 身份验证算法。




== 了解更多信息

* https://github.com/NetApp/trident["Astra Trident GitHub"^]
* https://netapp.io/persistent-storage-provisioner-for-kubernetes/["Astra Trident 博客"^]

