---
sidebar: sidebar 
permalink: trident-use/ontap-san.html 
keywords: trident backend, ontap san, ontap-san, ontap-san-economy, fsx, drivers, access modes, rwo, rwx, rwp, rwop, file system 
summary: 了解如何使用 ONTAP SAN 驱动程序配置 ONTAP 后端。 
---
= ONTAP SAN驱动程序概述
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解如何使用 ONTAP 和 Cloud Volumes ONTAP SAN 驱动程序配置 ONTAP 后端。



== ONTAP SAN驱动程序详细信息

Asta三端存储提供了以下SAN存储驱动程序、用于与ONTAP集群进行通信。支持的访问模式包括：_ReadWriteOnce_(RWO)、_ReadOnlyMany_(ROX)、_ReadWriteMany_(rwx)、_ReadWriteOncePod_(RWOP)。


IMPORTANT: 如果您使用Astra Control进行保护、恢复和移动、请阅读 <<Astra Control驱动程序兼容性>>。

[cols="2, 1, 1, 2, 2"]
|===
| 驱动程序 | 协议 | 卷模式 | 支持的访问模式 | 支持的文件系统 


| `ontap-san`  a| 
iSCSI
 a| 
块
 a| 
Rwo、ROX、rwx、RWOP
 a| 
无文件系统；原始块设备



| `ontap-san`  a| 
iSCSI
 a| 
文件系统
 a| 
Rwo、RWO1.

Rox和rwx在文件系统卷模式下不可用。
 a| 
`xfs` ， `ext3` ， `ext4`



| `ontap-san`  a| 
NVMe/TCP

请参见 <<NVMe/TCP的其他注意事项>>。
 a| 
块
 a| 
Rwo、ROX、rwx、RWOP
 a| 
无文件系统；原始块设备



| `ontap-san`  a| 
NVMe/TCP

请参见 <<NVMe/TCP的其他注意事项>>。
 a| 
文件系统
 a| 
Rwo、RWO1.

Rox和rwx在文件系统卷模式下不可用。
 a| 
`xfs` ， `ext3` ， `ext4`



| `ontap-san-economy.`  a| 
iSCSI
 a| 
块
 a| 
Rwo、ROX、rwx、RWOP
 a| 
无文件系统；原始块设备



| `ontap-san-economy.`  a| 
iSCSI
 a| 
文件系统
 a| 
Rwo、RWO1.

Rox和rwx在文件系统卷模式下不可用。
 a| 
`xfs` ， `ext3` ， `ext4`

|===


=== Astra Control驱动程序兼容性

Astra Control可为使用创建的卷提供无缝保护、灾难恢复和移动性(在Kubernetes集群之间移动卷) `ontap-nas`， `ontap-nas-flexgroup`，和 `ontap-san` 驱动程序。请参见 link:https://docs.netapp.com/us-en/astra-control-center/use/replicate_snapmirror.html#replication-prerequisites["Astra Control复制前提条件"^] 了解详细信息。

[WARNING]
====
* 使用 ... `ontap-san-economy` 只有当永久性卷使用量计数预期高于时、才会显示此值 link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["支持的ONTAP卷限制"^]。
* 使用 ... `ontap-nas-economy` 只有当永久性卷使用量计数预期高于时、才会显示此值 link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["支持的ONTAP卷限制"^] 和 `ontap-san-economy` 无法使用驱动程序。
* 请勿使用 `ontap-nas-economy` 预测数据保护、灾难恢复或移动性的需求。


====


== 用户权限

Astra Trident 应以 ONTAP 或 SVM 管理员身份运行，通常使用 `admin` cluster 用户或 `vsadmin` SVM 用户，或者使用具有相同角色的其他名称的用户。对于适用于 NetApp ONTAP 的 Amazon FSX 部署， Astra Trident 应使用集群 `fsxadmin` user 或 `vsadmin` SVM 用户或具有相同角色的其他名称的用户作为 ONTAP 或 SVM 管理员运行。`fsxadmin` 用户是集群管理员用户的有限替代用户。


NOTE: 如果使用 `limitAggregateUsage` 参数，则需要集群管理员权限。将适用于 NetApp ONTAP 的 Amazon FSx 与 Astra Trident 结合使用时， `limitAggregateUsage` 参数不适用于 `vsadmin` 和 `fsxadmin` 用户帐户。如果指定此参数，配置操作将失败。

虽然可以在ONTAP中创建一个可以由三端驱动程序使用的限制性更强的角色、但我们不建议这样做。大多数新版本的 Trident 都会调用需要考虑的其他 API ，从而使升级变得困难且容易出错。



== NVMe/TCP的其他注意事项

Asta三端存储器支持使用的非易失性内存快速(NVMe)协议 `ontap-san` 驱动程序包括：

* IPv6
* NVMe卷的快照和克隆
* 调整NVMe卷大小
* 导入在Asta Trident外部创建的NVMe卷、以便Asta Trident可以管理其生命周期
* NVMe本机多路径
* 正常或非正常关闭K8s节点(24.06)


Astra三项技术不支持：

* DH-HMAC-CHAP、由NVMe本机提供支持
* 设备映射程序(Device maper、DM)多路径
* 进行了加密

