---
sidebar: sidebar 
permalink: trident-use/trident-fsx-install-trident.html 
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident add-on, Astra Trident EKS add-on, Trident AWS EKS add-on 
summary: '通过将Asta三端存储与Amazon FSx for NetApp ONTAP 结合使用、您可以确保在Amazon Elastic Kubelnetes Service (EKS)中运行的Kubelnetes集群可以配置ONTAP 支持的块和文件永久性卷。' 
---
= 安装 Astra Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Asta三端存储简化了Kubelnetes中适用于NetApp ONTAP存储的Amazon FSx管理、使开发人员和管理员能够专注于应用程序部署。

您可以使用以下方法之一安装Astra Trident：

* 掌舵
* EKS附加项


[listing]
----
If you want to make use of the snapshot functionality, install the CSI snapshot controller add-on. Refer to https://docs.aws.amazon.com/eks/latest/userguide/csi-snapshot-controller.html.
----


== 通过Helm安装Asta Trident

使用以下环境变量设置*云提供程序*和*云身份*标志的值：

`export CP="AWS"`
`export CI="'eks.amazonaws.com/role-arn: arn:aws:iam::<accountID>:role/<AmazonEKS_FSxN_CSI_DriverRole>'"`

以下示例将安装Asta Dent并设置 `cloud-provider` 标记为 `$CP`，和 `cloud-identity` to `$CI`：

[listing]
----
helm install trident trident-operator-100.2406.0.tgz --set cloudProvider=$CP --set cloudIdentity=$CI -–namespace trident
----


== 通过EKS插件安装Astra Trident

A作用 是通过AWS验证、可与Amazon EKS配合使用。通过EKS加载项、您可以始终确保Amazon EKS集群安全稳定、并减少安装、配置和更新加载项所需的工作量。



=== 前提条件

在配置适用于AWS EKS的Asta TrIDent加载项之前、请确保满足以下条件：

* 具有附加订阅的Amazon EKS集群帐户
* AWS对AWS Marketplace的权限：
`"aws-marketplace:ViewSubscriptions",
"aws-marketplace:Subscribe",
"aws-marketplace:Unsubscribe`
* AMI类型：Amazon Linux 2 (AL2_x86_64)或Amazon Linux 2 ARM (AL2_ARM_64)
* 节点类型：AMD或ARM
* 现有Amazon FSx for NetApp ONTAP文件系统




=== 启用适用于AWS的Asta Trident加载项

[role="tabbed-block"]
====
.EKS集群
--
以下示例命令用于安装Asta Trdent EKS加载项：

`eksctl create addon --cluster clusterName --name netapp_trident-operator --version v24.02.0-eksbuild.`
`eksctl create addon --cluster clusterName --name netapp_trident-operator --version v24.02.0-eksbuild.1` (使用专用版本)

--
.管理控制台
--
. 打开Amazon EKS控制台，网址为 https://console.aws.amazon.com/eks/home#/clusters[]。
. 在左侧导航窗格中，单击*群集*。
. 单击要为其配置NetApp Trident CSI加载项的集群的名称。
. 单击*Add-ones*，然后单击*Get more add-ones*。
. 在*S*择 加载项*页上，执行以下操作：
+
.. 在AWS Marketplace EKS-addons部分中、选中* NetApp Trident by Astra*复选框。
.. 单击 * 下一步 * 。


. 在“*配置选定的附加项*设置”页面上，执行以下操作：
+
.. 选择要使用的*版本*。
.. 对于*Select IAM Role*，保留为*not set*。
.. 展开*可选配置设置*，遵循*附加配置架构*，并将*配置值*部分中的configurationvalues*参数设置为您在上一步中创建的roole-arn (值格式应为： `eks.amazonaws.com/role-arn: arn:aws:iam::464262061435:role/AmazonEKS_FSXN_CSI_DriverRole`)。如果您为冲突解决方法选择覆盖、则可以使用Amazon EKS附加设置覆盖现有附加项的一个或多个设置。如果未启用此选项、并且与现有设置存在冲突、则操作将失败。您可以使用生成的错误消息来解决冲突。在选择此选项之前、请确保Amazon EKS附加组件未管理您需要自行管理的设置。


. 选择“*下一步*”。
. 在*Review and add*页上，选择*Cree*。
+
加载项安装完成后、您将看到已安装的加载项。



--
.AWS命令行界面
--
. 创建 `add-on.json` 文件：
+
[listing]
----
add-on.json
{

   "clusterName": "<eks-cluster>",
   "addonName": "netapp_trident-operator",
   "addonVersion": "v24.2.0-eksbuild.1",
   "serviceAccountRoleArn": "arn:aws:iam::123456:role/astratrident-role",
   "configurationValues": "{"cloudIdentity": "'eks.amazonaws.com/role-arn: arn:aws:iam::123456:role/astratrident-role'"}"
}
----
. 安装Astra Trident EKS附加软件"
+
`aws eks create-addon --cli-input-json file://add-on.json`



--
====


=== 更新Astra Trident EKS加载项

[role="tabbed-block"]
====
.EKS集群
--
* 检查FSxN Trident CSI加载项的当前版本。请替换 `my-cluster` 为您的集群名称。
`eksctl get addon --name netapp_trident-operator --cluster my-cluster`
+
*示例输出：*



[listing]
----
NAME                        VERSION             STATUS    ISSUES    IAMROLE    UPDATE AVAILABLE    CONFIGURATION VALUES
netapp_trident-operator    v24.2.0-eksbuild.1    ACTIVE    0       {"cloudIdentity":"'eks.amazonaws.com/role-arn: arn:aws:iam::139763910815:role/AmazonEKS_FSXN_CSI_DriverRole'"}
----
* 将此加载项更新到上一步输出中的update下返回的版本。
`eksctl update addon --name netapp_trident-operator --version v24.2.0-eksbuild.1 --cluster my-cluster --force`
+
如果您删除了该 `--force` 选项、并且任何Amazon EKS附加设置与您的现有设置冲突、则更新Amazon EKS附加设置将失败；您将收到一条错误消息、以帮助您解决冲突。在指定此选项之前、请确保Amazon EKS附加组件不会管理您需要管理的设置、因为这些设置会被此选项覆盖。有关此设置的其他选项的详细信息，请参见 link:https://eksctl.io/usage/addons/["插件"]。有关Amazon EKS Kubenetes字段管理的详细信息，请参阅 link:https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-field-management.html["Kubbernetes现场管理"]。



--
.管理控制台
--
. 打开Amazon EKS控制台 https://console.aws.amazon.com/eks/home#/clusters[]。
. 在左侧导航窗格中，单击*群集*。
. 单击要更新的NetApp Trident CSI加载项的集群的名称。
. 单击*Add-ones*选项卡。
. 单击*Asta Trident by NetApp (Asta编辑)*，然后单击*Edit*(编辑*)。
. 在*Configure Astra Trident by Astr* NetApp页上，执行以下操作：
+
.. 选择要使用的*版本*。
.. (可选)您可以展开*可选配置设置*并根据需要进行修改。
.. 单击 * 保存更改 * 。




--
.AWS命令行界面
--
以下示例将更新EKS加载项：

`aws eks update-addon --cluster-name my-cluster netapp_trident-operator vpc-cni --addon-version v24.2.0-eksbuild.1 \
    --service-account-role-arn arn:aws:iam::111122223333:role/role-name --configuration-values '{}' --resolve-conflicts --preserve`

--
====


=== 卸载/删除Asta Trident EKS加载项

您可以通过两种方式删除Amazon EKS附加项：

* *保留集群上的附加软件*–此选项将删除Amazon EKS对任何设置的管理。此外、它还会使Amazon EKS无法通知您更新、并在您启动更新后自动更新Amazon EKS附加项。但是、它会保留集群上的附加软件。此选项可使附加组件成为自管理安装、而不是Amazon EKS附加组件。通过此选项、此附加组件不会出现停机。保留命令中的 `--preserve` 选项以保留此附加项。
* *从您的集群中完全删除附加软件*–我们建议您仅在集群中没有依赖于此附加软件的资源时、才从集群中删除此附加软件。从命令中删除 `--preserve` 此选项 `delete` 以删除此加载项。



NOTE: 如果此附加项具有关联的IAM帐户、则不会删除此IAM帐户。

[role="tabbed-block"]
====
.EKS集群
--
以下命令将卸载Asta三端EKS加载项：
`eksctl delete addon --cluster K8s-arm --name netapp_trident-operator`

--
.管理控制台
--
. 打开Amazon EKS控制台，网址为 https://console.aws.amazon.com/eks/home#/clusters[]。
. 在左侧导航窗格中，单击*群集*。
. 单击要删除的NetApp Trident CSI加载项的集群的名称。
. 单击*Add-ons*选项卡，然后单击*Astra Trident by NetApp。*
. 单击 * 删除 * 。
. 在*Remove NetApp_trdent-operator con確 認*对话框中，执行以下操作：
+
.. 如果您希望Amazon EKS停止管理此附加组件的设置、请选择*保留集群*。如果要在集群上保留附加软件、以便您可以自行管理附加软件的所有设置、请执行此操作。
.. 输入*NetApp_trdent-operator*。
.. 单击 * 删除 * 。




--
.AWS命令行界面
--
请使用集群的名称进行替换 `my-cluster` 、然后运行以下命令。

`aws eks delete-addon --cluster-name my-cluster --addon-name netapp_trident-operator --preserve`

--
====