---
sidebar: sidebar 
permalink: trident-use/trident-fsx-prep.html 
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident 
summary: '您可以将适用于NetApp ONTAP 的Amazon FSX文件系统与Astra Trident集成、以确保在Amazon Elastic Kubernetes Service (EKS)中运行的Kubernetes集群可以配置由ONTAP 提供支持的块和文件永久性卷。' 
---
= 集成适用于NetApp ONTAP 的Amazon FSX
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以将适用于NetApp ONTAP 的Amazon FSX文件系统与Astra Trident集成、以确保在Amazon Elastic Kubernetes Service (EKS)中运行的Kubernetes集群可以配置由ONTAP 提供支持的块和文件永久性卷。

.开始之前
此外 link:../trident-get-started/requirements.html["Astra Trident 要求"]要将适用于ONTAP 的FSx与Astra Trident集成、您需要：

* 已安装 `kubectl` 的现有 Amazon EKS 集群或自管理 Kubernetes 集群。
* 可从集群的工作节点访问的适用于 NetApp ONTAP 文件系统和 Storage Virtual Machine （ SVM ）的现有 Amazon FSX 。
* 为准备工作的工作节点 link:worker-node-prep.html["NFS或iSCSI"]。
+

NOTE: 确保按照Amazon Linux和Ubuntu所需的节点准备步骤进行操作 https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html["Amazon Machine 映像"^] （ AMIS ），具体取决于您的 EKS AMI 类型。



.SMB卷的其他要求
* 一个Kubernetes集群、其中包含一个Linux控制器节点以及至少一个运行Windows Server 2019的Windows工作节点。Astra Trident仅支持将SMB卷挂载到Windows节点上运行的Pod。
* 至少一个包含Active Directory凭据的Astra Trident密钥。以生成密钥 `smbcreds`：
+
[listing]
----
kubectl create secret generic smbcreds --from-literal username=user --from-literal password='pw'
----
* 配置为Windows服务的CSI代理。配置 `csi-proxy`、请参见 link:https://github.com/kubernetes-csi/csi-proxy["GitHub：CSI代理"^] 或 link:https://github.com/Azure/aks-engine/blob/master/docs/topics/csi-proxy-windows.md["GitHub：适用于Windows的CSI代理"^] 适用于在Windows上运行的Kubernetes节点。




== ONTAP SAN和NAS驱动程序集成


WARNING: 如果要为SMB卷配置、则必须读取 <<准备配置SMB卷>> 创建后端之前。

.步骤
. 使用其中一种部署Astra Trident link:../trident-get-started/kubernetes-deploy.html["部署方法"]。
. 收集SVM管理LIF DNS名称。例如、使用AWS命令行界面查找 `DNSName` 下的条目 `Endpoints` -> `Management` 运行以下命令后：
+
[listing]
----
aws fsx describe-storage-virtual-machines --region <file system region>
----
. 创建和安装证书 link:ontap-nas-prep.html["NAS后端身份验证"] 或 link:ontap-san-prep.html["SAN后端身份验证"]。
+

NOTE: 您可以从可以访问文件系统的任何位置使用 SSH 登录到文件系统（例如，安装证书）。使用 `fsxadmin` 用户，创建文件系统时配置的密码以及 `AWS FSx describe 文件系统` 中的管理 DNS 名称。

. 使用您的证书和管理 LIF 的 DNS 名称创建后端文件，如以下示例所示：
+
[listing]
----
{
  "version": 1,
  "storageDriverName": "ontap-san",
  "backendName": "customBackendName",
  "managementLIF": "svm-XXXXXXXXXXXXXXXXX.fs-XXXXXXXXXXXXXXXXX.fsx.us-east-2.aws.internal",
  "svm": "svm01",
  "clientCertificate": "ZXR0ZXJwYXB...ICMgJ3BhcGVyc2",
  "clientPrivateKey": "vciwKIyAgZG...0cnksIGRlc2NyaX",
  "trustedCACertificate": "zcyBbaG...b3Igb3duIGNsYXNz",
 }
----
+
有关创建后端的信息，请参见以下链接：

+
** link:ontap-nas.html["使用 ONTAP NAS 驱动程序配置后端"]
** link:ontap-san.html["使用 ONTAP SAN 驱动程序配置后端"]




.结果
部署完成后、您可以创建 link:../trident-get-started/kubernetes-postdeployment.html["存储类，配置卷以及将卷挂载到 Pod 中"]。



== 准备配置SMB卷

您可以使用配置SMB卷 `ontap-nas` 驱动程序。完成前 <<ONTAP SAN和NAS驱动程序集成>> 完成以下步骤。

.步骤
. 创建SMB共享。您可以使用以下两种方式之一创建SMB管理共享 link:https://learn.microsoft.com/en-us/troubleshoot/windows-server/system-management-components/what-is-microsoft-management-console["Microsoft管理控制台"^] 共享文件夹管理单元或使用ONTAP 命令行界面。要使用ONTAP 命令行界面创建SMB共享、请执行以下操作：
+
.. 如有必要，为共享创建目录路径结构。
+
。 `vserver cifs share create` 命令会在创建共享期间检查-path选项中指定的路径。如果指定路径不存在，则命令将失败。

.. 创建与指定SVM关联的SMB共享：
+
[listing]
----
vserver cifs share create -vserver vserver_name -share-name share_name -path path [-share-properties share_properties,...] [other_attributes] [-comment text]
----
.. 验证是否已创建共享：
+
[listing]
----
vserver cifs share show -share-name share_name
----
+

NOTE: 请参见 link:https://docs.netapp.com/us-en/ontap/smb-config/create-share-task.html["创建 SMB 共享"^] 了解完整详细信息。



. 创建后端时、必须配置以下内容以指定SMB卷。有关适用于ONTAP 后端的所有FSX配置选项、请参见 link:trident-fsx-examples.html["适用于ONTAP 的FSX配置选项和示例"]。
+
[cols="3"]
|===
| 参数 | Description | 示例 


| `smbShare` | 使用共享文件夹Microsoft管理控制台创建的SMB共享的名称。例如"smb-share"。*对于SMB卷为必需项。* | "smb-share" 


| `nasType` | *必须设置为 `smb`如果为空、则默认为 `nfs`。 | "SMB" 


| `securityStyle` | 新卷的安全模式。对于SMB卷、*必须设置为"NTFS"。* | "NTFS" 


| `unixPermissions` | 新卷的模式。对于SMB卷、*必须留空。* | "" 
|===

