---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-customize-deploy.html 
keywords: deploy, trident, methods, operator, tridentctl, helm, attributes, customize, tridentorchestrator, smb, windows 
summary: '使用 Trident 操作符，您可以使用 `TridentOrchestrator` 规范中的属性自定义 Astra Trident 的安装方式。' 
---
= 自定义Trident操作员安装
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用Trident操作员可以使用中的属性自定义Astra Trident安装 `TridentOrchestrator` 规格如果您要对安装进行自定义、使其超出预期范围 `TridentOrchestrator` 参数允许、请考虑使用 `tridentctl` 生成自定义YAML清单以根据需要进行修改。



== 了解控制器Pod和节点Pod

Astra Trident作为一个控制器POD运行、并在集群中的每个工作节点上运行一个节点POD。节点POD必须在任何可能要挂载Astra Trident卷的主机上运行。

Kubernetes link:https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/["节点选择器"^] 和 link:https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/["容忍和损害"^] 用于限制Pod在特定节点或首选节点上运行。使用`ControllerPlugin`和 `NodePlugin`、您可以指定约束和覆盖。

* 控制器插件负责卷配置和管理、例如快照和调整大小。
* 节点插件负责将存储连接到节点。




== 配置选项


WARNING: `spec.namespace` 在中指定 `TridentOrchestrator` 表示安装了Astra Trident的命名空间。此参数 * 安装 Astra Trident 后无法更新 * 。如果尝试执行此操作、则会导致 `TridentOrchestrator` 要更改为的状态 `Failed`。Astra Trident不能跨命名空间迁移。

此表详细介绍了相关信息 `TridentOrchestrator` 属性。

[cols="3"]
|===
| 参数 | Description | Default 


| `命名空间` | 用于安装 Astra Trident 的命名空间 | default 


| `debug` | 为 Astra Trident 启用调试 | false 


| `windows` | 设置为 `true` 启用在Windows工作节点上的安装。 | false 


| `IPv6` | 安装基于 IPv6 的 Astra Trident | false 


| `k8sTimeout` | Kubernetes 操作超时 | 30 秒 


| `sileAutoSupport` | 不要自动向 NetApp 发送 AutoSupport 捆绑包 | false 


| `enableNodePrep` | 自动管理工作节点依赖关系（ * 测试版 * ） | false 


| `autosupport 映像` | AutoSupport 遥测的容器映像 | "NetApp/trident自动支持：23.01" 


| `autosupport 代理` | 用于发送 AutoSupport 遥测的代理的地址 / 端口 | "http://proxy.example.com:8888"[] 


| `卸载` | 用于卸载 Astra Trident 的标志 | false 


| `logFormat` | 要使用的 Astra Trident 日志记录格式 [text ， json] | 文本 


| `TridentImage` | 要安装的 Astra Trident 映像 | "NetApp/Trident ： 21.04" 


| `imageRegistry` | 内部注册表的路径，格式为 ` < 注册表 FQDN>[ ：端口 ]/subpath]` | "K8s.gcr.io/SIG-storage (K8s 1.19+)或quay.io/k8scsi " 


| `kubeletDir` | 主机上的 kubelet 目录的路径 | "/var/lib/kubelet" 


| `wipeout` | 要删除以执行 Astra Trident 完全删除的资源列表 |  


| `imagePullSecs` | 从内部注册表中提取映像的机密信息 |  


| `imagePullPolicy` | 设置Trident运算符的映像提取策略。有效值为：
`Always` 以始终提取映像。
`IfNotPresent` 仅当节点上尚不存在映像时才提取该映像。
`Never` 从不提取映像。 | `IfNotPresent` 


| `控制器插件节点选择器` | Pod的其他节点选择器。格式与 pod.spec.nodeSelector 相同。 | 无默认值；可选 


| `控制器插件公差` | 覆盖Kubernetes对Pod的容错。格式与 po.spec.Tolerations 相同。 | 无默认值；可选 


| `nodePluginNodeSelector` | Pod的其他节点选择器。格式与 pod.spec.nodeSelector 相同。 | 无默认值；可选 


| `nodePluginTholeations` | 覆盖Kubernetes对Pod的容错。格式与 po.spec.Tolerations 相同。 | 无默认值；可选 
|===

NOTE: 有关格式化 POD 参数的详细信息，请参见 link:https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/["将 Pod 分配给节点"^]。



== 配置示例

您可以在定义时使用上述属性 `TridentOrchestrator` 自定义安装。

.示例1：基本自定义配置
[%collapsible%open]
====
这是一个基本自定义配置示例。

[listing]
----
cat deploy/crds/tridentorchestrator_cr_imagepullsecrets.yaml
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  imagePullSecrets:
  - thisisasecret
----
====
.示例2：使用节点选择器部署
[%collapsible%open]
====
此示例说明了如何使用节点选择器部署Trident：

[listing]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  controllerPluginNodeSelector:
    nodetype: master
  nodePluginNodeSelector:
    storage: netapp
----
====
.示例3：在Windows工作节点上部署
[%collapsible%open]
====
此示例说明了如何在Windows工作节点上部署。

[listing]
----
cat deploy/crds/tridentorchestrator_cr.yaml
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  windows: true
----
====