---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy-tridentctl.html 
keywords: deploy, astra trident, methods, tridentctl, windows 
summary: '您可以使用安装Astra Trident `tridentctl`。此过程将处理适用场景 安装、其中、Astra Trident所需的容器映像是否存储在专用注册表中。' 
---
= 使用tridentctl进行安装
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用安装Astra Trident `tridentctl`。此过程将处理适用场景 安装、其中、Astra Trident所需的容器映像是否存储在专用注册表中。以自定义 `tridentctl` 部署、请参见 link:kubernetes-customize-deploy-tridentctl.html["自定义 tridentctl 部署"]。



== 有关Astra Trdent 23.04的重要信息

*您必须阅读以下有关Astra Trident的重要信息。*

.<strong> 中有关Astra </strong> 的信息
[%collapsible%open]
====
* 现在、在Trident中支持Kubnetes 1.27。在升级Kubernetes之前升级Trident。
* Astra Trident会严格强制在SAN环境中使用多路径配置、建议值为 `find_multipaths: no` 在multipath.conf文件中。
+
使用非多路径配置或 `find_multipaths: yes` 或 `find_multipaths: smart` multipath.conf文件中的值将导致挂载失败。Trident已建议使用 `find_multipaths: no` 自21.07版起。



====


== 使用安装Astra Trident `tridentctl`

请查看 link:../trident-get-started/kubernetes-deploy.html["安装概述"] 以确保满足安装前提条件并为您的环境选择正确的安装选项。

.开始之前
开始安装之前、请登录到Linux主机并验证它是否正在管理一个正常运行的、 link:requirements.html["支持的 Kubernetes 集群"^] 并且您拥有必要的特权。


NOTE: 使用 OpenShift 时，在以下所有示例中使用 `oc` 而不是 `kubectl` ，并首先以 * 系统： admin* 的身份运行 `oc login -u system ： admin` 或 `oc login -u Kube-admin` 进行登录。

[%collapsible%open]
====
. 验证Kubernetes版本：
+
[listing]
----
kubectl version
----
. 验证集群管理员权限：
+
[listing]
----
kubectl auth can-i '*' '*' --all-namespaces
----
. 验证您是否可以从Docker Hub启动使用映像的POD并通过POD网络访问存储系统：
+
[listing]
----
kubectl run -i --tty ping --image=busybox --restart=Never --rm -- \
  ping <management IP>
----


====


== 第1步：下载Trident安装程序包

Astra Trident安装程序包可创建Trident Pod、配置用于保持其状态的CRD对象、并初始化CSI sidecars以执行配置卷以及将卷附加到集群主机等操作。从下载并提取最新版本的Trident安装程序 link:https://github.com/NetApp/trident/releases/latest["GitHub上的_assets_部分"^]。在示例中、使用选定的<trident-installer-XX.XX.X.tar.gz> Trident版本更新_Astra Trident。

[listing]
----
wget https://github.com/NetApp/trident/releases/download/v23.04.0/trident-installer-23.04.0.tar.gz
tar -xf trident-installer-23.04.0.tar.gz
cd trident-installer
----


== 第2步：安装Astra Trident

通过执行在所需命名空间中安装Astra Trident `tridentctl install` 命令：您可以添加其他参数来指定映像注册表位置。

[role="tabbed-block"]
====
.标准模式
--
[listing]
----
./tridentctl install -n trident
----
--
.一个注册表中的映像
--
[listing]
----
./tridentctl install -n trident --image-registry <your-registry> --autosupport-image <your-registry>/trident-autosupport:23.04 --trident-image <your-registry>/trident:23.04.0
----
--
.不同注册表中的映像
--
您必须附加 `sig-storage` 到 `imageRegistry` 使用不同的注册表位置。

[listing]
----
./tridentctl install -n trident --image-registry <your-registry>/sig-storage --autosupport-image <your-registry>/netapp/trident-autosupport:23.04 --trident-image <your-registry>/netapp/trident:23.04.0
----
--
====
您的安装状态应如下所示。

[listing]
----
....
INFO Starting Trident installation.                namespace=trident
INFO Created service account.
INFO Created cluster role.
INFO Created cluster role binding.
INFO Added finalizers to custom resource definitions.
INFO Created Trident service.
INFO Created Trident secret.
INFO Created Trident deployment.
INFO Created Trident daemonset.
INFO Waiting for Trident pod to start.
INFO Trident pod started.                          namespace=trident pod=trident-controller-679648bd45-cv2mx
INFO Waiting for Trident REST interface.
INFO Trident REST interface is up.                 version=23.04.0
INFO Trident installation succeeded.
....
----


== 验证安装。

您可以使用POD创建状态或验证安装 `tridentctl`。



=== 正在使用POD创建状态

您可以通过查看已创建Pod的状态来确认Astra Trident安装是否已完成：

[listing]
----
kubectl get pods -n trident

NAME                                  READY   STATUS    RESTARTS   AGE
trident-controller-679648bd45-cv2mx   6/6     Running   0          5m29s
trident-node-linux-vgc8n              2/2     Running   0          5m29s
----

NOTE: 如果安装程序未成功完成或 `trident-controller-<generated id>` (`trident-csi-<generated id>` 在23.01之前的版本中)不具有*正在运行*状态、表示未安装此平台。使用 ... `-d` to link:../troubleshooting.html#troubleshooting-an-unsuccessful-trident-deployment-using-tridentctl["打开调试模式"] 并对问题描述 进行故障排除。



=== 使用 `tridentctl`

您可以使用 `tridentctl` 检查安装的Astra Trident版本。

[listing]
----
./tridentctl -n trident version

+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 23.04.0        | 23.04.0        |
+----------------+----------------+
----


== 配置示例

.示例1：启用A作用 于Windows节点的Asta三端到子
[%collapsible%open]
====
要在Windows节点上运行A作用 是：

[listing]
----
tridentctl install --windows -n trident
----
====
.示例2：启用force detach
[%collapsible%open]
====
有关强制断开的详细信息、请参见 link:..trident-get-started/kubernetes-customize-deploy.html["自定义Trident操作员安装"]。

[listing]
----
tridentctl install --enable-force-detach=true -n trident
----
====


== 下一步行动

现在可以了 link:kubernetes-postdeployment.html["创建创建后端和存储类、配置卷并将卷挂载到Pod中"]。
