---
sidebar: sidebar 
permalink: trident-concepts/ontap-drivers.html 
keywords: trident backend, AFF, FAS, ONTAP Select, Cloud, Amazon FSx for NetApp ONTAP, drivers, ONTAP drivers 
summary: 了解如何在 Trident 安装中创建和使用 Element 后端。 
---
= ONTAP 驱动程序
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Astra Trident 提供了五个唯一的 ONTAP 存储驱动程序，用于与 ONTAP 集群进行通信。详细了解每个驱动程序如何处理卷的创建，访问控制及其功能。



== 了解ONTAP 存储驱动程序


WARNING: 客户必须使用 `ontap-nas` 适用于需要数据保护、灾难恢复和移动性的生产工作负载的驱动程序。Astra Control可为使用创建的卷提供无缝保护、灾难恢复和移动性 `ontap-nas` 驱动程序。。 `ontap-nas-economy` 驱动程序仅适用于预期卷使用量远高于ONTAP 支持的有限使用情形、并且没有预期的数据保护、灾难恢复或移动性(在Kubernetes集群之间移动卷)要求。

[cols="5"]
|===
| 驱动程序 | 协议 | 卷模式 | 支持的访问模式 | 支持的文件系统 


| `ontap-NAS`  a| 
NFS
 a| 
文件系统
 a| 
rwo ， rox ， rwx
 a| 
"" ， NFS



| `ontap-nas-economy.`  a| 
NFS
 a| 
文件系统
 a| 
rwo ， rox ， rwx
 a| 
"" ， NFS



| `ontap-nas-flexgroup`  a| 
NFS
 a| 
文件系统
 a| 
rwo ， rox ， rwx
 a| 
"" ， NFS



| `ontap-san`  a| 
iSCSI
 a| 
块
 a| 
rwo ， rox ， rwx
 a| 
无文件系统；原始块设备



| `ontap-san`  a| 
iSCSI
 a| 
文件系统
 a| 
工单， ROX

rwx在文件系统卷模式下不可用。
 a| 
`xfs` ， `ext3` ， `ext4`



| `ontap-san-economy.`  a| 
iSCSI
 a| 
块
 a| 
rwo ， rox ， rwx
 a| 
无文件系统；原始块设备



| `ontap-san-economy.`  a| 
iSCSI
 a| 
文件系统
 a| 
工单， ROX

rwx在文件系统卷模式下不可用。
 a| 
`xfs` ， `ext3` ， `ext4`

|===

NOTE: 可以使用安全角色的登录凭据(用户名/密码)或使用ONTAP 集群上安装的私钥和证书对ONTAP 后端进行身份验证。您可以使用更新现有后端以从一种身份验证模式移至另一种身份验证模式 `tridentctl update backend`。
