---
sidebar: sidebar 
permalink: trident-reco/backup.html 
keywords: data protection, replication, dr, disaster recovery, snapmirror, back up, snapshot, element, volume replication 
summary: 了解Asta三元数据以及使用Asta三元数据创建的卷的保护和恢复选项。对于具有持久性要求的每个应用程序，您都应制定一个数据保护和恢复策略。 
---
= 数据保护和灾难恢复
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解Asta三元数据以及使用Asta三元数据创建的卷的保护和恢复选项。对于具有持久性要求的每个应用程序，您都应制定一个数据保护和恢复策略。



== Astra三元数据复制和恢复

您可以创建备份、以便在发生灾难时还原Asta三端存储。



=== Astra三项技术复制

Astra Tandent使用Kubnetes CRD存储和管理自己的状态、并使用Kubnetes集群etcd存储其元数据。

.步骤
. 使用备份Kubenetes集群etcd  link:https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#backing-up-an-etcd-cluster["Kubenetes：备份etcd集群"^]。
. 将备份项目放在FlexVol上。
+

NOTE: 建议您保护FlexVol所在的SVM、并将其与另一个SVM建立SnapMirror关系。





=== Asta三元组恢复

您可以使用Kubenetes CRD和Kubenetes集群etcd快照来恢复Astra Trident。

.步骤
. 从目标SVM中、将包含Kubnetes etcd数据文件和证书的卷挂载到将设置为主节点的主机上。
. 在下复制与Kubirnetes集群相关的所有必需证书 `/etc/kubernetes/pki` 和下的etcd成员文件 `/var/lib/etcd`。
. 使用从etcd备份还原Kubenetes集群 link:https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#restoring-an-etcd-cluster["Kubornetes：还原etcd集群"^]。
. 运行 `kubectl get crd` 验证所有的三端测试自定义资源是否已启动、并检索三端测试对象以验证所有数据是否可用。




== SVM复制和恢复

Asta三端存储无法配置复制关系、但存储管理员可以使用 https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-svm-replication-concept.html["ONTAP SnapMirror"^] 复制SVM。

发生灾难时，您可以激活 SnapMirror 目标 SVM 以开始提供数据。系统还原后、您可以切换回主系统。

.关于此任务
使用SnapMirror SVM复制功能时、请考虑以下事项：

* 您应为启用了SVM-DR的每个SVM创建一个不同的后端。
* 将存储类配置为仅在需要时选择复制的后端、以避免将不需要复制的卷配置到支持SVM-DR的后端。
* 应用程序管理员应了解与复制相关的额外成本和复杂性、并在开始此过程之前仔细考虑其恢复计划。




=== SVM复制

您可以使用 link:https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-svm-replication-workflow-concept.html["ONTAP：SnapMirror SVM复制"^] 以创建SVM复制关系。

使用SnapMirror、您可以设置选项来控制要复制的内容。您需要知道在预成形时选择了哪些选项 <<使用Asta Trdent恢复SVM>>。

* link:https://docs.netapp.com/us-en/ontap/data-protection/replicate-entire-svm-config-task.html["-Identity保留true"^] 复制整个SVM配置。
* link:https://docs.netapp.com/us-en/ontap/data-protection/exclude-lifs-svm-replication-task.html["-discard-configs network"^] 不包括LIP和相关网络设置。
* link:https://docs.netapp.com/us-en/ontap/data-protection/exclude-network-name-service-svm-replication-task.html["-Identity保留false"^] 仅复制卷和安全配置。




=== 使用Asta Trdent恢复SVM

Astra Trident 不会自动检测 SVM 故障。如果发生灾难、管理员可以手动启动通过三项功能故障转移到新SVM的操作。

.步骤
. 取消计划的和正在进行的SnapMirror传输、中断复制关系、停止源SVM、然后激活SnapMirror目标SVM。
. 如果指定了 `-identity-preserve false` 或 `-discard-config network` 配置SVM复制时、请更新 `managementLIF` 和 `dataLIF` 在三端定义文件中。
. 确认 `storagePrefix` 位于三端定义文件中。无法更改此参数。正在放弃 `storagePrefix` 发生原因后端更新是否会失败。
. 使用以下命令更新所有必需的后端、以反映新的目标SVM名称：
+
[listing]
----
./tridentctl update backend <backend-name> -f <backend-json-file> -n <namespace>
----
. 如果指定了 `-identity-preserve false` 或 `discard-config network`，则必须退回所有应用程序Pod。
+

NOTE: 如果指定了 `-identity-preserve true`、则A作用 是在激活目标SVM后、A作用 是通过Asta Trident配置的所有卷都会开始提供数据。





== 卷复制和恢复

Asta三端存储无法配置SnapMirror复制关系、但存储管理员可以使用 link:https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-disaster-recovery-concept.html["ONTAP SnapMirror复制和恢复"^] 以复制Asta Trdent创建的卷。

然后、您可以使用将恢复的卷导入到Astra Trident中 link:../trident-use/vol-import.html["tridentctrd卷导入"]。


NOTE: 不支持导入 `ontap-nas-economy`，  `ontap-san-economy`或 `ontap-flexgroup-economy` 驱动程序。



== Snapshot数据保护

您可以使用以下方式保护和还原数据：

* 外部快照控制器和CRD、用于为永久性卷(PVs)创建Kubbernetes卷快照。
+
link:../trident-use/vol-snapshots.html["卷快照"]

* ONTAP快照、用于还原卷的全部内容或恢复单个文件或LUN。
+
link:https://docs.netapp.com/us-en/ontap/data-protection/manage-local-snapshot-copies-concept.html["ONTAP快照"^]





== Astra Control Center应用程序复制

使用Astra Control、您可以使用SnapMirror的异步复制功能将数据和应用程序更改从一个集群复制到另一个集群。

link:https://docs.netapp.com/us-en/astra-control-center/use/replicate_snapmirror.html["Astra Control：使用SnapMirror技术将应用程序复制到远程系统"^]
