---
sidebar: sidebar 
permalink: trident-reference/rest-api.html 
keywords: rest api, get, post, json, object, backends 
summary: 如果您希望与 Astra Trident 的 REST API 进行交互，则可以直接使用 REST 端点。 
---
= Astra Trident REST API
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
同时 link:tridentctl.html["tridentctl 命令和选项"] 是与Astra Trident REST API交互的最简单方式、您可以根据需要直接使用REST端点。



== 何时使用REST API

REST API适用于在非Kubernetes部署中使用Astra Trident作为独立二进制文件的高级安装。

为了提高安全性、我们使用了Astra Trident `REST API` 默认情况下、在Pod内部运行时、仅限于localhost。要更改此行为、您需要设置Astra Trident `-address` 参数。



== 使用REST API

有关如何调用这些API的示例、请通过调试 (`-d`)标志。有关详细信息，请参见 link:../trident-managing-k8s/tridentctl.html["使用tridentct利 管理Astra三端"]。

API 的工作原理如下：



=== 获取

`GET <trident-address>/trident/v1/<object-type>`:: 列出该类型的所有对象。
`GET <trident-address>/trident/v1/<object-type>/<object-name>`:: 获得命名对象的详细信息。




=== 发布

`POST <trident-address>/trident/v1/<object-type>`:: 创建指定类型的对象。
+
--
* 需要为要创建的对象配置 JSON 。有关每种对象类型的规范、请参见 link:../trident-managing-k8s/tridentctl.html["使用tridentct利 管理Astra三端"]。
* 如果对象已存在，则行为会有所不同：后端更新现有对象，而所有其他对象类型将使操作失败。


--




=== 删除

`DELETE <trident-address>/trident/v1/<object-type>/<object-name>`:: 删除命名资源。
+
--

NOTE: 与后端或存储类关联的卷将继续存在；必须单独删除这些卷。有关详细信息，请参见 link:../trident-managing-k8s/tridentctl.html["使用tridentct利 管理Astra三端"]。

--

